### ISSUE TITLE
Interactive program does not work for workshop on August 31,

### ISSUE THREAD

**Issue by kiszk** [VLDB2020/VLDB2020.github.io#117]
When I click multiple slots for workshops on August 31 from the interactive menu at https://vldb2020.org/program.html, the program does not appear. I conformed it with Firefox, Chrome, and Safari on MacOS.

For example, the content does not appear for W2_1, W1_7, and W2_7. On the other hand, flat version can show the contents (e.g. https://vldb2020.org/program_flat.html?s=W1_7#).

**Comment by abarth500** [comment]
There is no detail program on the interactive program.
The workshop program is managed by workshop web pages themselves. Hopefully :-)
....But they don't...
I will ask to the workshop chair ,Professor Onizuka.

I've included a video link for the flat program for the worst case.

**Comment by kiszk** [comment]
I see. Is this blank intentional on the interactive menu?

![image](https://user-images.githubusercontent.com/1315079/91663444-d0f01880-eb23-11ea-8c78-ec647de0b61d.png)

**Comment by kiszk** [comment]
I have another question. How each participant can get the link to a slot of a workshop (e.g. https://vldb2020.org/program_flat.html?s=W1_7#). The link https://vldb2020.org/program_flat.html? shows the very long flat program.

If to click a time slot on the interactive program can navigate to the link (e.g. https://vldb2020.org/program_flat.html?s=W1_7#), it would be great.

**Comment by abarth500** [comment]
Workshop programs are not managed in the main meeting every year. 
Participants must go to workshop Web pages to see the program.

However, this year is a little complicated. 
We don't manage workshop programs, but we manage workshop videos and Zoom links. I told the workshop chair all the URLs they need for the workshop program. So they can create a workshop program with Zoom, Slack, YouTube BiliBili links. If there are no links on the workshop program. Please ask to the workshop chair or the workshop organizers.

All links must be shown on the workshop's web page, not on the main conference program.
Here is an example of PhD Workshop: https://vldb2020.org/program_phdworkshop.html

**Comment by kiszk** [comment]
I see. Got it. It would be good to eliminate the large blank. This is because I expected something would be filled when I see this at first.

**Comment by abarth500** [comment]
Thank you for the comment. I agree with you. Or, I should put something in the blank :-)
