### ISSUE TITLE
https://vldb2020.org/program_flat.html?s=W2_7# misses contents

### ISSUE THREAD

**Issue by kiszk** [VLDB2020/VLDB2020.github.io#118]
[This web page] misses multiple contents:
- W2_7-1
- Links to video on Youtube.

**Comment by abarth500** [comment]
Thank you!
I'm working on it.

**Comment by kiszk** [comment]
Thank you. Now. it works.

![image](https://user-images.githubusercontent.com/1315079/91663395-85d60580-eb23-11ea-9313-ce15a0fea67b.png)
